services:
  billing-service:
    build: .
    ports:
      - "4005:4005"
    env_file:
      - .env
    depends_on:
      - mongo-billing
    networks:
      - hm-net

  mongo-billing:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27022:27017"
    volumes:
      - mongo-billing-data:/data/db
    networks:
      - hm-net

volumes:
  mongo-billing-data:

networks:
  hm-net:

