services:
  auth-service:
    platform: linux/amd64
    build: ./backend/auth-service
    ports:
      - "4001:4001"
    env_file:
      - ./backend/auth-service/.env
    depends_on:
      - mongo-auth
    networks:
      - hm-net

  appointment-service:
    platform: linux/amd64
    build: ./backend/appointment-service
    ports:
      - "4002:4002"
    env_file:
      - ./backend/appointment-service/.env
    volumes:
      - appointment-uploads:/app/uploads
    depends_on:
      - mongo-appointment
    networks:
      - hm-net

  doctor-service:
    platform: linux/amd64
    build: ./backend/doctor-service
    ports:
      - "4003:4003"
    env_file:
      - ./backend/doctor-service/.env
    depends_on:
      - mongo-doctor
    networks:
      - hm-net

  lab-service:
    platform: linux/amd64
    build: ./backend/lab-service
    ports:
      - "4004:4004"
    env_file:
      - ./backend/lab-service/.env
    volumes:
      - lab-uploads:/app/uploads
    depends_on:
      - mongo-lab
    networks:
      - hm-net

  billing-service:
    platform: linux/amd64
    build: ./backend/billing-service
    ports:
      - "4005:4005"
    env_file:
      - ./backend/billing-service/.env
    volumes:
      - billing-uploads:/app/uploads
    depends_on:
      - mongo-billing
    networks:
      - hm-net

  api-gateway:
    platform: linux/amd64
    build: ./backend/api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./backend/api-gateway/.env
    depends_on:
      - auth-service
      - appointment-service
      - doctor-service
      - lab-service
      - billing-service
    networks:
      - hm-net

  mongo-auth:
    platform: linux/amd64
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-auth-data:/data/db
    networks:
      - hm-net

  mongo-appointment:
    platform: linux/amd64
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongo-appointment-data:/data/db
    networks:
      - hm-net

  mongo-doctor:
    platform: linux/amd64
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - mongo-doctor-data:/data/db
    networks:
      - hm-net

  mongo-lab:
    platform: linux/amd64
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27021:27017"
    volumes:
      - mongo-lab-data:/data/db
    networks:
      - hm-net

  mongo-billing:
    platform: linux/amd64
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27022:27017"
    volumes:
      - mongo-billing-data:/data/db
    networks:
      - hm-net

networks:
  hm-net:

volumes:
  mongo-auth-data:
  mongo-appointment-data:
  mongo-doctor-data:
  mongo-lab-data:
  mongo-billing-data:
  appointment-uploads:
  lab-uploads:
  billing-uploads:


