services:
  doctor-service:
    build: .
    ports:
      - "4003:4003"
    env_file:
      - .env
    depends_on:
      - mongo-doctor
    networks:
      - hm-net

  mongo-doctor:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - mongo-doctor-data:/data/db
    networks:
      - hm-net

volumes:
  mongo-doctor-data:

networks:
  hm-net:

