services:
  lab-service:
    build: .
    ports:
      - "4004:4004"
    env_file:
      - .env
    depends_on:
      - mongo-lab
    networks:
      - hm-net

  mongo-lab:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27021:27017"
    volumes:
      - mongo-lab-data:/data/db
    networks:
      - hm-net

volumes:
  mongo-lab-data:

networks:
  hm-net:

